name: Build Docker images on native runners

on:
  push:
    branches:
      - Ubuntu24

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd Docker
          docker build --platform linux/${{ matrix.platform }} -t ${{ secrets.DOCKER_USERNAME }}/exp:24-${{ matrix.platform }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/exp:24-${{ matrix.platform }}
