name: Build Docker images on native runners

on:
  push:
    branches:
      - Ubuntu24

env:
  REGISTRY_IMAGE: the9cat/exp
  TAG: 24

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-24.04
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd Docker
          docker build --platform linux/${{ matrix.platform }} -t ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}-${{ matrix.platform }} .
          docker push ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}-${{ matrix.platform }}

  post-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }} \
          ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}-amd64 \
          ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}-arm64
          docker manifest push ${{ env.REGISTRY_IMAGE }}:${{ env.TAG }}
